# Generated by Django 4.1.7 on 2023-04-24 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Twiddit_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('followedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='Twiddit_profile.user')),
                ('followerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='Twiddit_profile.user')),
            ],
        ),
    ]
