# Generated by Django 4.1.7 on 2023-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twiddit_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
